// Full-canvas narrative event overlay, drawn over the paused (dimmed) world.
//
// Shows a Victorian field-journal entry generated by the NarrativeEngine, with
// two choice buttons. While the API call is still in flight it shows an animated
// loading line instead. Records button rects so main.js can hitTest() pointer
// events and resolve the chosen consequence. Pure canvas rendering — no DOM.

import { COLORS, FONTS, font, text, panel, rgba } from '../utils/renderer.js';
import { isBeneficialConsequence } from '../narrative/NarrativeEngine.js';

export class EventUI {
  constructor() {
    this._buttons = []; // { index, x, y, w, h }
  }

  /** Returns the chosen choice index, or null if (x,y) hit nothing. */
  hitTest(px, py) {
    for (const b of this._buttons) {
      if (px >= b.x && px <= b.x + b.w && py >= b.y && py <= b.y + b.h) {
        return b.index;
      }
    }
    return null;
  }

  draw(ctx, event, loading, w, h) {
    this._buttons = [];

    ctx.save();

    // Dim the world underneath.
    ctx.fillStyle = 'rgba(20, 18, 16, 0.78)';
    ctx.fillRect(0, 0, w, h);

    // Centered parchment panel (scales down on small canvases).
    const pw = Math.min(w - 32, 480);
    const ph = Math.min(h - 32, 340);
    const px = (w - pw) / 2;
    const py = (h - ph) / 2;
    panel(ctx, px, py, pw, ph, { fill: COLORS.parchment, stroke: COLORS.ink, lineWidth: 3, radius: 14 });

    // Botanical ink illustration: a quill writing in an open journal.
    this._drawQuill(ctx, px + pw / 2, py + 34);

    if (!event) {
      // Loading state — animated ellipsis where the text block will appear.
      const dots = '.'.repeat(1 + Math.floor((Date.now() / 400) % 3));
      text(ctx, `Consulting the field notes${dots}`, px + pw / 2, py + ph / 2 + 10, {
        fontStr: `italic ${font(FONTS.body, 14)}`,
        color: rgba(COLORS.ink, 0.7),
      });
      ctx.restore();
      return;
    }

    // Title.
    text(ctx, event.title, px + pw / 2, py + 64, {
      fontStr: font(FONTS.title, 22, '600'),
      color: COLORS.ink,
    });

    // Divider.
    ctx.strokeStyle = rgba(COLORS.ink, 0.4);
    ctx.lineWidth = 1;
    ctx.beginPath();
    ctx.moveTo(px + 40, py + 80);
    ctx.lineTo(px + pw - 40, py + 80);
    ctx.stroke();

    // Body text (line-wrapped).
    this._wrapText(ctx, event.text, px + pw / 2, py + 102, Math.min(pw - 48, 420), 19, {
      fontStr: font(FONTS.body, 14),
      color: COLORS.ink,
    });

    // Choice buttons — side by side on wide canvases, stacked on narrow ones.
    const choices = event.choices.slice(0, 2);
    const gap = 12;
    const btnH = 62;
    const bottom = py + ph - 16;
    const stacked = pw < 460;
    const bx0 = px + 24;

    choices.forEach((choice, i) => {
      let bx;
      let by;
      let bw;
      if (stacked) {
        bw = pw - 48;
        bx = bx0;
        by = bottom - btnH * (2 - i) - gap * (1 - i);
      } else {
        bw = (pw - 48 - gap) / 2;
        bx = bx0 + i * (bw + gap);
        by = bottom - btnH;
      }
      this._drawChoice(ctx, choice, bx, by, bw, btnH);
      this._buttons.push({ index: i, x: bx, y: by, w: bw, h: btnH });
    });

    ctx.restore();
  }

  _drawChoice(ctx, choice, x, y, w, h) {
    panel(ctx, x, y, w, h, {
      fill: rgba(COLORS.gold, 0.1),
      stroke: COLORS.ink,
      lineWidth: 1.6,
      radius: 8,
    });
    const cx = x + w / 2;
    text(ctx, choice.label, cx, y + 15, {
      fontStr: font(FONTS.title, 16, '700'),
      color: COLORS.ink,
    });
    text(ctx, choice.description, cx, y + 32, {
      fontStr: `italic ${font(FONTS.body, 11)}`,
      color: rgba(COLORS.ink, 0.75),
    });
    const c = choice.consequence;
    if (c && c.description) {
      const good = isBeneficialConsequence(c);
      text(ctx, c.description, cx, y + 48, {
        fontStr: font(FONTS.mono, 11, '700'),
        color: good ? COLORS.gold : COLORS.crimson,
      });
    }
  }

  // Small quill-in-journal illustration, centered at (cx, cy).
  _drawQuill(ctx, cx, cy) {
    ctx.save();
    ctx.translate(cx, cy);
    ctx.strokeStyle = COLORS.ink;
    ctx.lineWidth = 1.4;
    // open journal
    ctx.fillStyle = rgba(COLORS.parchmentSoft, 1);
    ctx.beginPath();
    ctx.moveTo(-22, 8);
    ctx.quadraticCurveTo(0, 2, 22, 8);
    ctx.lineTo(22, 14);
    ctx.quadraticCurveTo(0, 8, -22, 14);
    ctx.closePath();
    ctx.fill();
    ctx.stroke();
    // spine
    ctx.beginPath();
    ctx.moveTo(0, 5);
    ctx.lineTo(0, 12);
    ctx.stroke();
    // quill (diagonal feather)
    ctx.beginPath();
    ctx.moveTo(-2, 6);
    ctx.lineTo(16, -16);
    ctx.stroke();
    ctx.fillStyle = rgba(COLORS.ink, 0.85);
    ctx.beginPath();
    ctx.moveTo(16, -16);
    ctx.quadraticCurveTo(10, -10, 7, -6);
    ctx.quadraticCurveTo(13, -10, 16, -16);
    ctx.fill();
    ctx.restore();
  }

  // Minimal centered word-wrap helper.
  _wrapText(ctx, str, cx, y, maxWidth, lineHeight, opts) {
    ctx.save();
    ctx.font = opts.fontStr;
    const words = String(str).split(' ');
    const lines = [];
    let cur = '';
    for (const word of words) {
      const test = cur ? `${cur} ${word}` : word;
      if (ctx.measureText(test).width > maxWidth && cur) {
        lines.push(cur);
        cur = word;
      } else {
        cur = test;
      }
    }
    if (cur) lines.push(cur);
    ctx.restore();
    lines.forEach((ln, i) => text(ctx, ln, cx, y + i * lineHeight, opts));
  }
}
